
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/* @autor
 * — Estudiante: Cristian David Avila Narvaez.
 * — Código de estudiante: 1957500-2711
 * — Programación Interactiva.
 * — Grupo: Individual.
 */
public class IUCalculadora extends javax.swing.JFrame {

    /**
     * Creates new form IUCalculadora
     */
    public IUCalculadora() {
        initComponents();

        //Numeros, manejador de eventos.
        number0.addActionListener(new BTNNumberCERO());
        number1.addActionListener(new BTNNumberONE());
        number2.addActionListener(new BTNNumberTWO());
        number3.addActionListener(new BTNNumberTHREE());
        number4.addActionListener(new BTNNumberFOUR());
        number5.addActionListener(new BTNNumberFIVE());
        number6.addActionListener(new BTNNumberSIX());
        number7.addActionListener(new BTNNumberSEVEN());
        number8.addActionListener(new BTNNumberEIGHT());
        number9.addActionListener(new BTNNumberNINE());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        number8 = new javax.swing.JButton();
        number7 = new javax.swing.JButton();
        number9 = new javax.swing.JButton();
        number4 = new javax.swing.JButton();
        number6 = new javax.swing.JButton();
        number5 = new javax.swing.JButton();
        number1 = new javax.swing.JButton();
        number2 = new javax.swing.JButton();
        number0 = new javax.swing.JButton();
        punto = new javax.swing.JButton();
        number3 = new javax.swing.JButton();
        igualdad = new javax.swing.JButton();
        division = new javax.swing.JButton();
        suma = new javax.swing.JButton();
        buttonC = new javax.swing.JButton();
        resta = new javax.swing.JButton();
        multiplicacion = new javax.swing.JButton();
        buttonCE = new javax.swing.JButton();
        borrar = new javax.swing.JButton();
        txfContainer = new javax.swing.JTextField();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CALCULATOR");

        number8.setBackground(new java.awt.Color(51, 51, 51));
        number8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        number8.setText("8");

        number7.setBackground(new java.awt.Color(51, 51, 51));
        number7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        number7.setText("7");

        number9.setBackground(new java.awt.Color(51, 51, 51));
        number9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        number9.setText("9");

        number4.setBackground(new java.awt.Color(51, 51, 51));
        number4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        number4.setText("4");

        number6.setBackground(new java.awt.Color(51, 51, 51));
        number6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        number6.setText("6");

        number5.setBackground(new java.awt.Color(51, 51, 51));
        number5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        number5.setText("5");

        number1.setBackground(new java.awt.Color(51, 51, 51));
        number1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        number1.setText("1");

        number2.setBackground(new java.awt.Color(51, 51, 51));
        number2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        number2.setText("2");

        number0.setBackground(new java.awt.Color(51, 51, 51));
        number0.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        number0.setText("0");

        punto.setBackground(new java.awt.Color(51, 51, 51));
        punto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        punto.setText(".");

        number3.setBackground(new java.awt.Color(51, 51, 51));
        number3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        number3.setText("3");

        igualdad.setBackground(new java.awt.Color(51, 51, 51));
        igualdad.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        igualdad.setText("=");

        division.setBackground(new java.awt.Color(51, 51, 51));
        division.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        division.setText("/");

        suma.setBackground(new java.awt.Color(51, 51, 51));
        suma.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        suma.setText("+");

        buttonC.setBackground(new java.awt.Color(51, 51, 51));
        buttonC.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonC.setText("C");

        resta.setBackground(new java.awt.Color(51, 51, 51));
        resta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        resta.setText("-");

        multiplicacion.setBackground(new java.awt.Color(51, 51, 51));
        multiplicacion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        multiplicacion.setText("*");

        buttonCE.setBackground(new java.awt.Color(51, 51, 51));
        buttonCE.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonCE.setText("CE");

        borrar.setBackground(new java.awt.Color(51, 51, 51));
        borrar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        borrar.setText("DL");

        txfContainer.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txfContainer.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(number7, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(number8, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(number9, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(multiplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(number4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(number5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(number6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(resta, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(number1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(number2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(number3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(suma, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(number0, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(punto, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(igualdad, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonCE, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(buttonC, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(division, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txfContainer, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txfContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(division, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonCE, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonC, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(number7, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(number8, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(number9, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(multiplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(number4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(number5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(number6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resta, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(number1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(number2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(number3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(suma, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(number0, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(punto, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(igualdad, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IUCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IUCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IUCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IUCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IUCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borrar;
    private javax.swing.JButton buttonC;
    private javax.swing.JButton buttonCE;
    private javax.swing.JButton division;
    private javax.swing.JButton igualdad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton multiplicacion;
    private javax.swing.JButton number0;
    private javax.swing.JButton number1;
    private javax.swing.JButton number2;
    private javax.swing.JButton number3;
    private javax.swing.JButton number4;
    private javax.swing.JButton number5;
    private javax.swing.JButton number6;
    private javax.swing.JButton number7;
    private javax.swing.JButton number8;
    private javax.swing.JButton number9;
    private javax.swing.JButton punto;
    private javax.swing.JButton resta;
    private javax.swing.JButton suma;
    private javax.swing.JTextField txfContainer;
    // End of variables declaration//GEN-END:variables

    public class BTNNumberCERO implements ActionListener {

        public void actionPerformed(ActionEvent ae) {
            txfContainer.setText("0");
        }
    }

    public class BTNNumberONE implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            txfContainer.setText("1");
        }

    }

    public class BTNNumberTWO implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            txfContainer.setText("2");
        }

    }

    public class BTNNumberTHREE implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            txfContainer.setText("3");
        }

    }

    public class BTNNumberFOUR implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            txfContainer.setText("4");
        }

    }

    public class BTNNumberFIVE implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            txfContainer.setText("5");
        }

    }

    public class BTNNumberSIX implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            txfContainer.setText("6");
        }

    }

    public class BTNNumberSEVEN implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            txfContainer.setText("7");
        }

    }

    public class BTNNumberEIGHT implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            txfContainer.setText("8");
        }

    }

    public class BTNNumberNINE implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            txfContainer.setText("9");
        }
    }
}
